version: 2.1

orbs:
  node: circleci/node@2.1
  windows: circleci/windows@2.4

executors:
  linux:
    docker:
      - image: cimg/base:stable
  macos:
    macos:
      xcode: 11.4

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - node/install-packages
      - run: npm run test

workflows:
  matrix-tests:
    jobs:
      - test:
          matrix:
            parameters:
              os: [linux]
              node-version: ["latest", "latest-erbium", "latest-v14.x", "current", "lts", "14.2.0", "v14.2.0"]
