version: 2.1

orbs:
  node: circleci/node@2.1

jobs:
  test:
    parameters:
      node-version:
        type: string
    executor:
      name: node/default
      tag: << parameters.node-version >>
    steps:
      - run: npm version
      - checkout
      - node/install-packages
      - run: npm test

workflows:
  matrix-tests:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ["10.20.1", "12.16.3", "14.2.0"]
